# Generated by Django 5.0.6 on 2024-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_best_selling_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sluged_url',
            field=models.SlugField(default=''),
        ),
    ]
