# Generated by Django 5.0.6 on 2024-06-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_country_book_country_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country_book',
            field=models.ManyToManyField(null=True, to='book_outlet.country'),
        ),
    ]
