# Generated by Django 5.0.6 on 2024-06-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_loader_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_loader',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.sign_in'),
        ),
    ]
