# Generated by Django 5.0.6 on 2024-06-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_sign_in_email_remove_sign_in_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_in',
            old_name='username',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='task_loader',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.sign_in'),
        ),
    ]
