# Generated by Django 5.0.6 on 2024-06-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_username_sign_in_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_loader',
            name='phone',
        ),
        migrations.AddField(
            model_name='task_loader',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.sign_in'),
        ),
        migrations.AlterField(
            model_name='sign_in',
            name='id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
