# Generated by Django 5.0.6 on 2024-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_loader_phone_task_loader_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_in',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
